name: flutter_rust_bridge_test
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_rust_bridge: 2.5.0
  path_provider: ^2.1.4
  image: ^4.2.0
  ffi: ^2.1.3
  path: ^1.9.0
  rust_lib_flutter_rust_bridge_test:
    path: rust_builder
  device_info_plus: ^11.0.0
  system_tray: ^2.0.3
  bitsdojo_window: ^0.1.6
  english_words: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

assets:
  - assets/
