// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.5.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `run_with_elevated_privileges_windows`

String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

void takeS({required String path}) =>
    RustLib.instance.api.crateApiSimpleTakeS(path: path);

void listenToKeyboardsMain() =>
    RustLib.instance.api.crateApiSimpleListenToKeyboardsMain();

List<String> getRunningProcesses() =>
    RustLib.instance.api.crateApiSimpleGetRunningProcesses();

void fileSystemMonitor() =>
    RustLib.instance.api.crateApiSimpleFileSystemMonitor();
